{"immobiliare_id": "111167349", "title": "Terratetto unifamiliare via Brescia 20, Cedessano, Provaglio Val Sabbia", "type": "Terratetto unifamiliare | Intera propriet\u00e0", "floor": "Piano terra", "number_of_floors": "1", "elevator": "No", "living_space_mq": "206 m\u00b2 | commerciale 239 m\u00b2", "rooms": "5", "bedrooms": "4", "bathrooms": "2", "furnished": "Parzialmente Arredato", "balcony": "S\u00ec", "terrace": "S\u00ec", "garage_parking_space": "1 in box privato/box in garage, 2 in parcheggio/garage comune", "heating": "Autonomo", "global_id": "polyseme_id"}
{"immobiliare_id": "69679798", "title": "Rustico, da ristrutturare, 130 m\u00b2, Provaglio Val Sabbia", "type": "Rustico | Intera propriet\u00e0", "floor": "Piano rialzato", "number_of_floors": "3", "elevator": "No", "living_space_mq": "130 m\u00b2", "global_id": "polyseme_id"}
{"immobiliare_id": "76848224", "title": "Terratetto unifamiliare via Roma 16, Arveaco, Provaglio Val Sabbia", "type": "Terratetto unifamiliare | Intera propriet\u00e0 | Classe immobile media", "floor": "Piano terra, da 1 a 2", "number_of_floors": "1", "elevator": "No", "living_space_mq": "120 m\u00b2", "rooms": "3", "bedrooms": "1", "kitchen": "Cucina abitabile", "bathrooms": "2", "furnished": "S\u00ec", "balcony": "S\u00ec", "terrace": "No", "garage_parking_space": "1 in parcheggio/garage comune", "heating": "Autonomo, a radiatori, alimentato a metano", "global_id": "polyseme_id"}
{"immobiliare_id": "108485999", "title": "Casale via Canale, Provaglio Val Sabbia", "type": "Casale | Intera propriet\u00e0 | Classe immobile signorile", "floor": "Piano terra, da 1 a 2", "number_of_floors": "2", "elevator": "No", "living_space_mq": "401 m\u00b2", "rooms": "4", "bedrooms": "3", "kitchen": "Cucina abitabile", "bathrooms": "2", "furnished": "Parzialmente Arredato", "balcony": "S\u00ec", "terrace": "S\u00ec", "garage_parking_space": "4 in parcheggio/garage comune", "heating": "Autonomo", "global_id": "polyseme_id"}
{"immobiliare_id": "110442817", "title": "Rustico via Provinciale, Provaglio Val Sabbia", "type": "Rustico | Intera propriet\u00e0 | Classe immobile economica", "floor": "Piano terra", "number_of_floors": "1", "elevator": "No", "living_space_mq": "113 m\u00b2", "rooms": "4", "furnished": "No", "balcony": "No", "terrace": "No", "garage_parking_space": "2 in parcheggio/garage comune", "global_id": "polyseme_id"}
{"immobiliare_id": "99304218", "title": "Villa bifamiliare via Belvedere 9, Arveaco, Provaglio Val Sabbia", "type": "Villa bifamiliare | Intera propriet\u00e0", "floor": "Piano terra", "number_of_floors": "2", "living_space_mq": "160 m\u00b2", "balcony": "S\u00ec", "terrace": "S\u00ec", "garage_parking_space": "1 in box privato/box in garage", "global_id": "polyseme_id"}
{"immobiliare_id": "112408241", "title": "Villa unifamiliare via Brescia, Cedessano, Provaglio Val Sabbia", "type": "Villa unifamiliare | Intera propriet\u00e0 | Classe immobile signorile", "floor": "Piano terra", "number_of_floors": "2", "elevator": "No", "living_space_mq": "355 m\u00b2", "rooms": "5+", "bedrooms": "4", "kitchen": "Cucina abitabile", "bathrooms": "3", "furnished": "Parzialmente Arredato", "balcony": "S\u00ec", "terrace": "S\u00ec", "garage_parking_space": "2 in parcheggio/garage comune", "heating": "Autonomo, a radiatori, alimentato a metano", "air_conditioning": "Autonomo, freddo/caldo", "global_id": "polyseme_id"}
{"immobiliare_id": "99694920", "title": "Casa indipendente all'asta via Settima Brigata Matteotti 70, Provaglio Val Sabbia", "type": "Casa indipendente | Intera propriet\u00e0 | Classe immobile media", "floor": "Piano terra", "number_of_floors": "3", "elevator": "No", "living_space_mq": "358 m\u00b2", "rooms": "4", "bedrooms": "3", "balcony": "No", "terrace": "S\u00ec", "global_id": "polyseme_id"}
{"immobiliare_id": "112829469", "title": "Villa a schiera via VII Brigata Matteotti 56, Cesane, Provaglio Val Sabbia", "type": "Villa a schiera | Nuda propriet\u00e0", "floor": "Seminterrato, da 1 a 2", "number_of_floors": "3", "living_space_mq": "250 m\u00b2 | commerciale 256 m\u00b2", "rooms": "5", "bedrooms": "3", "bathrooms": "3", "garage_parking_space": "1 in box privato/box in garage", "heating": "Autonomo", "global_id": "polyseme_id"}
